faq/urls.py
from django.conf.urls import url

from faq.views import FaqIndexPage

urlpatterns = [
    url(r'^$', FaqIndexPage.as_view(), name='index'),
    url(r'^(?P<category_id>\d+?)$', FaqIndexPage.as_view(), name='category'),
    url(r'^faq_search/(?P<search_field>\w+?)$', 'faq.views.faq_search', name='search'),
]

super5/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from super5.views import IndexPage, StaticPage
from rest.urls import api_patterns

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    url(r'^password_reset/$', 'django.contrib.auth.views.password_reset', name='password_reset'),
    url(r'^password_reset_done/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
    url(
        r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'django.contrib.auth.views.password_reset_confirm', name='password_reset_confirm'
    ),
    url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete', name='password_reset_complete'),

    url(r'^blogs/', include('blogs.urls', namespace='blogs')),
    url(r'^trainings/', include('trainings.urls', namespace="trainings")),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
    url(r'^athletes/', include('athletes.urls', namespace="athletes")),
    url(r'^faq/', include('faq.urls', namespace="faq")),
    url(r'^extend_notifications/', include('extend_notifications.urls')),

    url(r'^rest/', include('rest.urls')),
    url(r'^api/', include(api_patterns)),

    url(r'^$', IndexPage.as_view(), name='index_page'),
    url(r'^author/$', StaticPage.as_view(template_name="static/author.html"), name='author'),
    url(r'^for-business/$', StaticPage.as_view(template_name="static/for_business.html"), name='for_business'),
    url(r'^privacy-policy/$', StaticPage.as_view(template_name="static/privacy_policy.html"), name='privacy_policy'),
    url(r'^how-it-works/$', StaticPage.as_view(template_name="static/how_it_works.html"), name='how_it_works'),
    url(r'^contacts/$', StaticPage.as_view(template_name="static/contacts.html"), name='contacts'),

    url(r'^redactor/', include('redactor.urls')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r"^notifications/", include('pinax.notifications.urls')),

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': "./media/"}),

    url(r'^api-auth/', include('rest_framework.urls',
                               namespace='rest_framework')),
]

trainings/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^diary/$', 'trainings.views.training_diary_current_month', name='diary_now'),
    url(r'^diary/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/$', views.DiaryTrainingsView.as_view(), name='diary'),
    url(r'^training/$', views.TrainingView.as_view(), name='training'),
]

trainings/models.py
from django.utils import timezone
from django.db import models
from athletes.models import Zone, Target
from super5 import settings


class Exercise(models.Model):

    LOW, LOW_MIDDLE, MIDDLE, HEIGHT, VERY_HIGH = 0, 1, 2, 3, 4
    LEVEL = (
        (LOW, 'Низкий'),
        (LOW_MIDDLE, 'Ниже среднего'),
        (MIDDLE, 'Средний'),
        (HEIGHT, 'Высокий'),
        (VERY_HIGH, 'Очень высокий')
    )

    title = models.CharField('Название', max_length=100, default='')
    description = models.TextField('Описание', default='')

    synchronous_vimeo_video_link = models.URLField('Ссылка на синхрон видео на вимео', blank=True, null=True)
    tutorial_vimeo_video_link = models.URLField('Ссылка на объясняющее видео на вимео', blank=True, null=True)

    difficulty = models.IntegerField(verbose_name='Сложность', blank=True, null=True, choices=LEVEL)
    zone = models.ForeignKey(Zone, verbose_name='Группа мышц', blank=True, null=True)
    target = models.ForeignKey(Target, verbose_name='Тип', blank=True, null=True)

    class Meta:
        verbose_name = 'Упражнение'
        verbose_name_plural = 'Упражнение'

    def __str__(self):
        return self.title


class WorkoutDiary(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)

    class Meta:
        verbose_name = 'Дневник тренировок'
        verbose_name_plural = 'Дневники тренировок'

    def __str__(self):
        return self.user.email

    def get(self):
        pass


class Training(models.Model):
    date = models.DateField(
        'Дата',
        default=timezone.now
    )
    result = models.TextField(
        'Результат',
        default='',
        blank=True,
        null=True
    )
    workout_diary = models.ForeignKey(
        'WorkoutDiary',
        verbose_name='Дневник тринировки'
    )

    class Meta:
        verbose_name = 'Тренировка'
        verbose_name_plural = 'Тренировки'

    def __str__(self):
        return "%s - %s" % (self.workout_diary, self.date)


class TrainingSet(models.Model):
    number_in_training = models.IntegerField(
        'Номер в тренировке'
    )
    exercises = models.ManyToManyField(
        'Exercise',
        verbose_name='Упражнения',
    )
    training = models.ForeignKey(
        'Training',
        verbose_name='Тренировка'
    )

    class Meta:
        verbose_name = 'Сет'
        verbose_name_plural = 'Сеты'

    def __str__(self):
        return str(self.number_in_training)

trainings/views.py
import pymorphy2

import json
from utils.funcs import chunks, add_months, sub_months, month_text

from calendar import Calendar, MONDAY
from datetime import datetime, date, timedelta
from django.views import generic
from django.shortcuts import redirect
from django.views.generic import TemplateView
from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response


from athletes.models import Athlete
from .serializations import TrainingSerializer
from .models import WorkoutDiary, Training

from athletes.serializations import AthleteAllDataSerializer


def get_training(user, current_date):
    try:
        return Training.objects.get(
            workout_diary__user=user,
            date=current_date
        )
    except Training.DoesNotExist:
        return None


class DiaryTrainingsView(generic.DetailView):
    model = WorkoutDiary
    template_name = 'trainings/diary.html'

    def get_object(self, queryset=None):
        return self.model.objects.get_or_create(user=self.request.user)[0]

    def get_context_data(self, **kwargs):

        def get_weekday_text(athlete, weekday):
            morph = pymorphy2.MorphAnalyzer()
            if athlete.week_day:
                for week_day in eval(athlete.week_day):
                    if weekday < int(week_day):
                        day_text = morph.parse(Athlete.WEEK_DAYS[int(week_day)][1])[0].inflect({'accs'}).word
                        return 'во' if Athlete.WEEK_DAYS[int(week_day)][0] == 1 else 'в', day_text
                day_text = morph.parse(Athlete.WEEK_DAYS[int(eval(athlete.week_day)[0])][1])[0].inflect({'accs'}).word
                return 'во' if Athlete.WEEK_DAYS[int(eval(athlete.week_day)[0])][0] == 1 else 'в', day_text
            return 'не', 'запланирована'

        athlete = Athlete.objects.get_or_create(user=self.request.user)[0]
        today = datetime.now().date()
        cal = Calendar(MONDAY)
        year = int(self.kwargs.get('year'))
        month = int(self.kwargs.get('month'))
        day = int(self.kwargs.get('day'))
        current_date = date(year, month, day)
        next_month = add_months(current_date, 1)
        prev_month = sub_months(current_date, 1)
        month_dates = list(cal.itermonthdates(year, month))
        trainings = Training.objects.filter(
            date__in=month_dates,
            workout_diary=self.object
        )
        month_dates_with_training = [
            (item, True) if athlete.week_day and item >= today
            and str(item.weekday()) in athlete.week_day
            else (item, trainings.filter(date=item).last())
            for item in month_dates
        ]
        splited = chunks(month_dates_with_training, 7)
        month = [(week[0][0].isocalendar()[1] == today.isocalendar()[1], week) for week in splited]
        training_today = athlete.week_day and (str(today.weekday()) in athlete.week_day)
        training = get_training(self.request.user, current_date)
        ctx = {
            'training': training,
            'today': today,
            'month': month,
            'prev_month': prev_month,
            'next_month': next_month,
            'current_month': month_text(current_date.month),
            'current_date': current_date,
            'current_weekday': Athlete.WEEK_DAYS[current_date.weekday()][1],
            'training_duration': athlete.get_training_duration_display(),
            'history': current_date < today,
            'training_today': training_today,
            'button_text': (True, 'Начать тренировку')
            if training_today else
            (False, 'Следующая тренировка %s %s' % get_weekday_text(athlete=athlete, weekday=today.weekday()))
        }
        return ctx


def get_training_queryset(user):
    return Training.objects.filter(
        workout_diary__user=user,
    )


class TrainingView(TemplateView):

    template_name = 'trainings/training.html'

    def get(self, request, *args, **kwargs):
        current_date = datetime.now().date()
        queryset = get_training_queryset(request.user).filter(current_date)
        serializer = TrainingSerializer(queryset, many=True)
        ctx = {
            'training': json.dumps(serializer.data),
            'current_date': current_date,
            'weekday': Athlete.WEEK_DAYS[current_date.weekday()][1],
        }
        return self.render_to_response(ctx)


class TrainingsViewSet(viewsets.ViewSet):
    permission_classes = (IsAuthenticated,)

    def list(self, request, format=None):
        current_date = datetime.now().date()
        from_date = self.request.query_params.get('from_date', datetime.now().date())
        to_date = self.request.query_params.get('to_date', datetime.now().date() + timedelta(days=7))
        get_training(self.request.user, current_date)
        return Response({
            'trainings': TrainingSerializer(
                get_training_queryset(self.request.user).filter(
                    date__gte=from_date, date__lte=to_date
                ),
                many=True,
                context={'request': self.request}
            ).data,
            'user_athlete': AthleteAllDataSerializer().to_representation(self.request.user.athlete)
        })


def training_diary_current_month(request):
    now = datetime.now()
    return redirect('trainings:diary', year=now.year, month=now.month, day=now.day)

templates/trainings/diary.html
{% extends 'super5_base_site.html' %}
{% load static %}

{% block title %}Super5 дневник тренировок{% endblock %}

{% block content %}
    <div class="all clearfix">
        <div class="content_container clearfix">
            <div class="title_black">дневник тренировок</div>
            <div class="calendarbig_container">
                <div class="calendar_top clearfix">
                    <a href="{% url 'trainings:diary' year=prev_month.year month=prev_month.month day=1%}" class="calendar_prev"></a>
                    <div class="calendar_title">
                        <div class="calendar_monthscore">Месячный результат: {{ calories }} Калл.</div>
                        <div class="calendar_monthyear">{{ current_month }} {{ current_date.year }}</div>
                    </div>
                    <a href="{% url 'trainings:diary' year=next_month.year month=next_month.month day=1 %}" class="calendar_next"></a>
                </div>
                <div class="calendar_content clearfix">

                    {% for current_week, week in month %}
                        <div class="cday_week_row clearfix {% if current_week %} active {% endif %}">
                            {% for day, training in week %}
                                {% if training %}
                                    {% if training.date %}
                                        <a href="{% url 'trainings:diary' year=training.date.year month=training.date.month day=training.date.day %}" class="cday day_active {% if not training.result and training.date != today %}cur_day{% endif %}"><span class="cd_num">{{ day.day }}</span><span class="cd_item"><span class="cd_time">{{ training_duration }}</span></span></a>
                                    {% else %}
                                        <div class="cday day_active"><span class="cd_num">{{ day.day }}</span><span class="cd_item"><span class="cd_time">{{ training_duration }}</span></span></div>
                                    {% endif %}
                                {% else %}
                                    <a href="{% url 'trainings:diary_now' %}" class="cday"><span class="cd_num">{{ day.day }}</span></a>
                                {% endif %}

                            {% endfor %}
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="calendar_day_container striped_bkg">
                <div class="cday_title">{{ training.date }}<span class="top_line"></span></div>
                <div class="cday_content clearfix">
                    {% for set in training.trainingset_set.all %}
                        {% for exercise in set.exercises.all %}
                            <a href="" class="cday_item"><div class="cday_item_photo"><img src="uploads/diary_photo1.png" width="100%" /></div><div class="cday_item_title">{{ exercise.title }}</div><div class="cday_item_time">5 min</div></a>
                        {% endfor %}
                    {% endfor %}
                </div>
                <div class="cday_btn_container">
                    {% if not history %}
                        <span class="bottom_line left_bottom_line"></span>
                        <a {% if training %} href="{% url 'trainings:training' %}" {% endif %} class="btn-workout -save">{{ button_text.1 }}</a>
                        <span class="bottom_line right_bottom_line"></span>
                    {% endif %}
                    <p class="justify_line"></p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/trainings/main.html
{% extends 'super5_base_site.html' %}
{% load static %}

{% block title %}Super5 основкая тренировка{% endblock %}

{% block content %}
    <div class="all clearfix">
        <div class="content_container clearfix">

            <div class="calendarbig_container">
                <div class="calendar_top clearfix">
                    <a href="" class="calendar_prev"></a>
                    <div class="calendar_title">
                        <div class="calendar_monthscore">Месячный результат: 7729 Кал.</div>
                        <div class="calendar_monthyear">Август 2014</div>
                    </div>
                    <a href=""  class="calendar_next"></a>
                </div>
                <div class="calendar_content clearfix">

                    <div class="cday_week_row clearfix">
                        <a href="" class="cday"><span class="cd_num">01</span></a>
                        <a href="" class="cday day_active"><span class="cd_num">02</span><span class="cd_item"><span class="cd_place">Зал</span><span class="cd_time">155 мин</span></span></a>
                        <a href="" class="cday"><span class="cd_num">03</span></a>
                        <a href="" class="cday day_active"><span class="cd_num">04</span><span class="cd_item"><span class="cd_place">Дом</span><span class="cd_time">15 мин</span></span></a>
                        <a href="" class="cday"><span class="cd_num">05</span></a>
                        <a class="cday day_active"><span class="cd_num">06</span><span class="cd_item"><span class="cd_place">Дом</span><span class="cd_time">15 мин</span></span></a>
                        <a class="cday day_active"><span class="cd_num">07</span><span class="cd_item"><span class="cd_place">Дом</span><span class="cd_time">15 мин</span></span></a>
                    </div>


                    <div class="cday_week_row active clearfix">
                        <a href="" class="cday day_active"><span class="cd_num">08</span><span class="cd_item"><span class="cd_place">Дом</span><span class="cd_time">15 мин</span></span></a>
                        <a href="" class="cday"><span class="cd_num">09</span></a>
                        <a href="" class="cday day_active"><span class="cd_num">10</span><span class="cd_item"><span class="cd_place">Дом</span><span class="cd_time">15 мин</span></span></a>
                        <a href="" class="cday"><span class="cd_num">11</span></a>
                        <a href="" class="cday day_active cur_day"><span class="cd_num">12</span><span class="cd_item"><span class="cd_place">Дом</span><span class="cd_time">15 мин</span></span></a>
                        <a href="" class="cday cur_day"><span class="cd_num">13</span></a>
                        <a href="" class="cday"><span class="cd_num">14</span></a>
                    </div>


                    <div class="cday_week_row clearfix">
                        <a href="" class="cday"><span class="cd_num">15</span></a>
                        <a href="" class="cday day_active"><span class="cd_num">16</span><span class="cd_item"><span class="cd_place">Зал</span><span class="cd_time">15 мин</span></span></a>
                        <a href="" class="cday"><span class="cd_num">17</span></a>
                        <a class="cday day_active"><span class="cd_num">18</span><span class="cd_item"><span class="cd_place">Дом</span><span class="cd_time">15 мин</span></span></a>
                        <a href="" class="cday"><span class="cd_num">19</span></a>
                        <a href="" class="cday day_active"><span class="cd_num">20</span><span class="cd_item"><span class="cd_place">Дом</span><span class="cd_time">15 мин</span></span></a>
                        <a href="" class="cday day_active"><span class="cd_num">21</span><span class="cd_item"><span class="cd_place">Дом</span><span class="cd_time">15 мин</span></span></a>
                    </div>



                    <div class="cday_week_row clearfix">
                        <a href="" class="cday day_active"><span class="cd_num">22</span><span class="cd_item"><span class="cd_place">Зал</span><span class="cd_time">15 мин</span></span></a>
                        <a href="" class="cday"><span class="cd_num">23</span></a>
                        <a href="" class="cday"><span class="cd_num">24</span></a>
                        <a class="cday day_active"><span class="cd_num">25</span><span class="cd_item"><span class="cd_place">Дом</span><span class="cd_time">15 мин</span></span></a>
                        <a href="" class="cday"><span class="cd_num">26</span></a>
                        <a href="" class="cday day_active"><span class="cd_num">27</span><span class="cd_item"><span class="cd_place">Дом</span><span class="cd_time">15 мин</span></span></a>
                        <a href="" class="cday day_active"><span class="cd_num">28</span><span class="cd_item"><span class="cd_place">Дом</span><span class="cd_time">15 мин</span></span></a>
                    </div>

                    <div class="cday_week_row clearfix">
                        <a href="" class="cday day_active"><span class="cd_num">29</span><span class="cd_item"><span class="cd_place">Зал</span><span class="cd_time">15 мин</span></span></a>
                        <a href="" class="cday"><span class="cd_num">30</span></a>
                        <a href="" class="cday"><span class="cd_num">31</span></a>
                    </div>
                </div>
            </div>
            <div class="workouts_container striped_bkg">
                <div class="workouts_title">
                    <a href="" class="cday_start_btn">Начать тренировку</a>
                    <span class="top_line_main"></span>
                    <!-- <div class="workouts_title_line"></div> -->Упражнения на сегодня
                </div>

                <div class="workouts_content clearfix">
                    <div class="flex_row">
                        <a href="" class="workouts_item">
                            <span class="workouts_item_photo"><img src="{% static 'uploads/diary_photo1.png' %}" width="100%" /></span>
                            <span class="workouts_item_title">cross fit - современная тренировка
                                <span class="workouts_item_desc">Здесь будет какой-либо текст</span>
                            </span>
                            <span class="workouts_item_time_container">
                            <span class="workouts_item_time">45 минут</span>
                            <span class="workouts_item_num">1</span></span>
                        </a>
                        <a href="" class="workouts_item">
                            <span class="workouts_item_photo"><img src="{% static 'uploads/diary_photo1.png' %}" width="100%" /></span>
                            <span class="workouts_item_title">cross fit - современная тренировка
                                <span class="workouts_item_desc">Здесь будет какой-либо текст</span>
                            </span>
                            <span class="workouts_item_time_container">
                            <span class="workouts_item_time">45 минут</span>
                            <span class="workouts_item_num">2</span></span>
                        </a>
                        <a href="" class="workouts_item">
                            <span class="workouts_item_photo"><img src="{% static 'uploads/diary_photo1.png' %}" width="100%" /></span>
                            <span class="workouts_item_title">cross fit - современная тренировка
                                <span class="workouts_item_desc">Здесь будет какой-либо текст</span>
                            </span>
                            <span class="workouts_item_time_container">
                            <span class="workouts_item_time">45 минут</span>
                            <span class="workouts_item_num">3</span></span>
                        </a>
                        <a href="" class="workouts_item">
                            <span class="workouts_item_photo"><img src="{% static 'uploads/diary_photo1.png' %}" width="100%" /></span>
                            <span class="workouts_item_title">cross fit - современная тренировка
                                <span class="workouts_item_desc">Здесь будет какой-либо текст</span>
                            </span>
                            <span class="workouts_item_time_container">
                            <span class="workouts_item_time">45 минут</span>
                            <span class="workouts_item_num">4</span></span>
                        </a>
                    </div>
                    <div class="flex_row">
                        <a href="" class="workouts_item">
                            <span class="workouts_item_photo"><img src="{% static 'uploads/diary_photo1.png' %}" width="100%" /></span>
                            <span class="workouts_item_title">cross fit - современная тренировка
                                <span class="workouts_item_desc">Здесь будет какой-либо текст</span>
                            </span>
                            <span class="workouts_item_time_container">
                            <span class="workouts_item_time">45 минут</span>
                            <span class="workouts_item_num">5</span></span>
                        </a>
                        <a href="" class="workouts_item paused">
                            <span class="workouts_item_time_container">
                            <span class="workouts_item_time">15 минут</span></span>
                        </a>
                        <a href="" class="workouts_item">
                            <span class="workouts_item_photo"><img src="{% static 'uploads/diary_photo1.png' %}" width="100%" /></span>
                            <span class="workouts_item_title">cross fit - современная тренировка
                                <span class="workouts_item_desc">Здесь будет какой-либо текст</span>
                            </span>
                            <span class="workouts_item_time_container">
                            <span class="workouts_item_time">45 минут</span>
                            <span class="workouts_item_num">7</span></span>
                        </a>
                        <a href="" class="workouts_item">
                            <span class="workouts_item_photo"><img src="{% static 'uploads/diary_photo1.png' %}" width="100%" /></span>
                            <span class="workouts_item_title">cross fit - современная тренировка
                                <span class="workouts_item_desc">Здесь будет какой-либо текст</span>
                            </span>
                            <span class="workouts_item_time_container">
                            <span class="workouts_item_time">45 минут</span>
                            <span class="workouts_item_num">8</span></span>
                        </a>
                    </div>
                </div>


                <div class="cday_btn_container">
                    <span class="bottom_line left_bottom_line"></span>
                    <a href="" class="cday_start_btn">начать тренировку</a>
                    <span class="bottom_line right_bottom_line"></span>
                    <p class="justify_line"></p>
                    <!-- <div class="cday_btn_container_after"></div> -->
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/trainings/training.html
{% extends 'super5_base_site.html' %}
{% load static %}

{% block title %}Super5 текущая тренировка{% endblock %}

{% block content %}
    <input type="hidden" name="training_response" value="{{ training }}">
    <div class="all clearfix">
        <div class="content_container clearfix">
            <div class="subtitle_red training_program"><p>Тренировочная программа сжигания жира день 17</p>
                <div class="subtitle_right">{{ weekday }} {{ current_date.day }}.{{ current_date.month }}</div>
            </div>
            <div class="subtitle_red trainer">тренер: Martin o’nail
                <a href="{% url 'trainings:diary_now' %}" class="subtitle_right">вернуться к календарю тренировок</a>
            </div>
            <div class="video_container">
                <div class="video_time">00:45:00</div>
                <div class="video_content">
                    <i class="video_content_before"></i>
                    <div class="video_preview">
						<div class="video_photo"><img src="{% static 'uploads/video_photo.jpg' %}" width="100%" /></div>
						<a href="#" class="btn-workout -start -abs">Начать тренировку</a>
                    </div>
					<div class="training-player-l hidden">
						<iframe id="player1" class="training-player active" src="" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
						<iframe id="player2" class="training-player hidden" src="" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
					</div>
                </div>
            </div>
            <div class="video_info">
                <div class="video_avtor clearfix">
                    <div class="vavtor_name">Marek Dabrowski
                        <div class="vavtor_address">Варшава  |  Польша  |  27</div>
                    </div>
                    <div class="vavtor_point">5.9</div>
                </div>
                <div class="vavtor_txt">Здесь будет какой-либо текст</div>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer_js %}
	<!--vimeo api-->
	<script src="https://f.vimeocdn.com/js/froogaloop2.min.js"></script>
	<!--vimeo js-->
	<script src="{% static 'js/vimeo.js' %}"></script>
{% endblock %}