faq/urls.py
from django.conf.urls import url

from faq.views import FaqIndexPage

urlpatterns = [
    url(r'^$', FaqIndexPage.as_view(), name='index'),
    url(r'^(?P<category_id>\d+?)$', FaqIndexPage.as_view(), name='category'),
    url(r'^faq_search/(?P<search_field>\w+?)$', 'faq.views.faq_search', name='search'),
]

super5/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from super5.views import IndexPage, StaticPage
from rest.urls import api_patterns

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    url(r'^password_reset/$', 'django.contrib.auth.views.password_reset', name='password_reset'),
    url(r'^password_reset_done/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
    url(
        r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'django.contrib.auth.views.password_reset_confirm', name='password_reset_confirm'
    ),
    url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete', name='password_reset_complete'),

    url(r'^blogs/', include('blogs.urls', namespace='blogs')),
    url(r'^trainings/', include('trainings.urls', namespace="trainings")),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
    url(r'^athletes/', include('athletes.urls', namespace="athletes")),
    url(r'^faq/', include('faq.urls', namespace="faq")),
    url(r'^extend_notifications/', include('extend_notifications.urls')),

    url(r'^rest/', include('rest.urls')),
    url(r'^api/', include(api_patterns)),

    url(r'^$', IndexPage.as_view(), name='index_page'),
    url(r'^author/$', StaticPage.as_view(template_name="static/author.html"), name='author'),
    url(r'^for-business/$', StaticPage.as_view(template_name="static/for_business.html"), name='for_business'),
    url(r'^privacy-policy/$', StaticPage.as_view(template_name="static/privacy_policy.html"), name='privacy_policy'),
    url(r'^how-it-works/$', StaticPage.as_view(template_name="static/how_it_works.html"), name='how_it_works'),
    url(r'^contacts/$', StaticPage.as_view(template_name="static/contacts.html"), name='contacts'),

    url(r'^redactor/', include('redactor.urls')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r"^notifications/", include('pinax.notifications.urls')),

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': "./media/"}),

    url(r'^api-auth/', include('rest_framework.urls',
                               namespace='rest_framework')),
]

faq/models.py
from django.db import models


class Category(models.Model):

    name = models.CharField(
        'Наименование категории',
        max_length=255,
    )

    class Meta:
        verbose_name = u'Категория'
        verbose_name_plural = u'Категории'

    def __str__(self):
        return self.name


class Question(models.Model):

    category = models.ForeignKey(
        Category,
        verbose_name=u'Категория',
        null=True,
        blank=True
    )
    email = models.EmailField(
        u'Электроннная почта',
        null=True,
        blank=True
    )
    text = models.TextField(
        u'Текст вопроса'
    )

    def __str__(self):
        return u'%s - %s' % (self.category.name, self.text)


class Answer(models.Model):

    question = models.OneToOneField(
        Question,
        verbose_name=u'Вопрос'
    )
    text = models.TextField(
        u'Текст ответа'
    )

    class Meta:
        verbose_name = u'Ответы'
        verbose_name_plural = u'Ответ'

    def __str__(self):
        return u'%s - %s' % (self.question.category.name, self.question.text)

faq/forms.py
from django import forms

from faq.models import Question, Category
from utils.widgets import CustomTextField


class QuestionForm(forms.ModelForm):

    email = forms.EmailField(
        widget=CustomTextField(placeholder='Super5 Email адрес')
    )

    category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        required=True
    )

    class Meta:
        model = Question
        fields = ['email', 'category', 'text']

    def __init__(self, **kwargs):
        super(QuestionForm, self).__init__(**kwargs)
        self.fields['text'].widget.attrs['class'] = 'textarea_field'

faq/views.py
from django.shortcuts import redirect, render_to_response
from django.views.generic import TemplateView
from faq.forms import QuestionForm
from faq.models import Category, Answer


class FaqIndexPage(TemplateView):

    template_name = 'faq/index.html'

    def __init__(self):
        super(FaqIndexPage, self).__init__()
        self.categories = Category.objects.all()
        self.answers = Answer.objects.none()
        self.form = QuestionForm()

    def get_context(self, request, **kwargs):
        category_id = kwargs.get('category_id', None)
        if category_id and not self.answers:
            self.answers = Answer.objects.filter(question__category_id=category_id)
        elif self.categories and not self.answers:
            self.answers = Answer.objects.all()
        context = {
            'categories': self.categories,
            'answers': self.answers,
            'form': self.form
        }
        return context

    def get(self, request, *args, **kwargs):
        return self.render_to_response(self.get_context(request, **kwargs))

    def post(self, request, *args, **kwargs):
        if 'search_field' in request.POST and request.POST['search_field']:
            return redirect('faq:search', search_field=request.POST['search_field'])
        else:
            self.form = QuestionForm(data=request.POST)
            ctx = self.get_context(request, **kwargs)
            if self.form.is_valid():
                self.form.save()
                self.form = QuestionForm()
                ctx.update(
                    {
                        'message': 'Ваш вопрос отправлен нашим специалистам, спасибо!'
                    }
                )
            return self.render_to_response(ctx)


def faq_search(request, search_field):
    answers = Answer.objects.filter(text__icontains=search_field)
    ctx = {
        'answers': answers,
        'message': 'Результаты поиска по запросу "%s"' % search_field,
        'categories': Category.objects.all(),
        'form': QuestionForm()
    }
    return render_to_response('faq/index.html', ctx)

templates/faq/index.html
{% extends 'super5_base_site.html' %}
{% load static %}

{% block title %}Super5 faq{% endblock %}

{% block content %}
    <div class="all with_left_column clearfix">
        <div class="content_container clearfix">
            <div class="title_grey">FAQ</div>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="search_container">
                    <div class="search_icon"></div>
                    <div class="search_field">
                        <input name="search_field" type="text">
                    </div>
                    <div class="search_btn">
                        <input name="search_btn" type="image" src="{% static 'images/btn_search.png' %}" value="">
                    </div>
                </div>
                <div class="left_column">
                    <ul class="left_submenu">
                        {% for category in categories %}
                            <li><a href="{% url 'faq:category' category_id=category.id %}">{{ category.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="faq_container">
					{% if message %}
					   <div class="faq_answer">
							{{ message }}
					   </div>
					{% endif %}
                    {% for answer in answers %}
                        <div class="faq_item">
                            <div class="faqitem_header">{{ answer.question.text }}</div>
                            <div class="faqitem_content">{{ answer.text }}</div>
                        </div>
                    {% endfor %}
                </div>
                <div class="faq_form clearfix">

                    <div class="form_row clearfix">
                       <div class="l-error-pos-rel -p-faq">
							{% if form.email.errors %}
								<div class="l-error-pos-abs">
									{{ form.email.errors }}
								</div>
							{% endif %}
							{{ form.email }}
                       </div>
                        <span class="and_simbol">&amp;</span>
                        <div class="l-error-pos-rel -p-faq">
							{% if form.category.errors %}
								<div class="l-error-pos-abs">
									{{ form.category.errors }}
								</div>
							{% endif %}
							{{ form.category }}
                        </div>
                        <p class="justify_line"></p>
                    </div>

                    <div class="form_row clearfix">
                        <div class="l-error-pos-rel -p-faq -textarea">
							{% if form.text.errors %}
								<div class="l-error-pos-abs">
									{{ form.text.errors }}
								</div>
							{% endif %}
							{{ form.text }}
                        </div>
                    </div>

                    <input type="submit" class="form_submit" value="Отправить">
                </div>
            </form>
        </div>
    </div>
{% endblock %}