accounts/urls.py
from django.conf.urls import url
from accounts.views import RegisterView, LoginView
from django.conf.urls import include

urlpatterns = [
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', 'accounts.views.logout', name='logout'),
    url(r'', include('athletes.urls')),
]

athletes/urls.py
from django.conf.urls import url

from .forms import (
    TargetPriorityForm, ZonePriorityForm,
    PriorityWizardFormStep1, PriorityWizardFormStep2,
    PriorityWizardFormStep3,
    PriorityWizardFormStep6)
from .views import PersonalData, PersonalDataWizardView, ChangeSomeField
from .views import change_priority

urlpatterns = [
    url(r'^personal-data/$', PersonalData.as_view(), name='personal_data'),
    url(r'^personal-data-master/$',
        PersonalDataWizardView.as_view([PriorityWizardFormStep1, PriorityWizardFormStep2,
                                        PriorityWizardFormStep3, TargetPriorityForm, ZonePriorityForm,
                                        PriorityWizardFormStep6]),
        name='personal_data_master'),
    url(r'^personal-data-master/change_priority/$', change_priority, name='change_priority'),
    url(r'^personal-data/change_priority/$', change_priority, name='change_priority_lk'),
    url(r'^personal-data/(?P<field>\w+)/$', ChangeSomeField.as_view(), name='change_field'),
]

blogs/urls.py
from django.conf.urls import url
from blogs.views import FeedView

urlpatterns = [
    url(r'^$', FeedView.as_view(), name='feed'),
]

faq/urls.py
from django.conf.urls import url

from faq.views import FaqIndexPage

urlpatterns = [
    url(r'^$', FaqIndexPage.as_view(), name='index'),
    url(r'^(?P<category_id>\d+?)$', FaqIndexPage.as_view(), name='category'),
    url(r'^faq_search/(?P<search_field>\w+?)$', 'faq.views.faq_search', name='search'),
]

super5/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from super5.views import IndexPage, StaticPage
from rest.urls import api_patterns

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    url(r'^password_reset/$', 'django.contrib.auth.views.password_reset', name='password_reset'),
    url(r'^password_reset_done/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
    url(
        r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'django.contrib.auth.views.password_reset_confirm', name='password_reset_confirm'
    ),
    url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete', name='password_reset_complete'),

    url(r'^blogs/', include('blogs.urls', namespace='blogs')),
    url(r'^trainings/', include('trainings.urls', namespace="trainings")),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
    url(r'^athletes/', include('athletes.urls', namespace="athletes")),
    url(r'^faq/', include('faq.urls', namespace="faq")),
    url(r'^extend_notifications/', include('extend_notifications.urls')),

    url(r'^rest/', include('rest.urls')),
    url(r'^api/', include(api_patterns)),

    url(r'^$', IndexPage.as_view(), name='index_page'),
    url(r'^author/$', StaticPage.as_view(template_name="static/author.html"), name='author'),
    url(r'^for-business/$', StaticPage.as_view(template_name="static/for_business.html"), name='for_business'),
    url(r'^privacy-policy/$', StaticPage.as_view(template_name="static/privacy_policy.html"), name='privacy_policy'),
    url(r'^how-it-works/$', StaticPage.as_view(template_name="static/how_it_works.html"), name='how_it_works'),
    url(r'^contacts/$', StaticPage.as_view(template_name="static/contacts.html"), name='contacts'),

    url(r'^redactor/', include('redactor.urls')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r"^notifications/", include('pinax.notifications.urls')),

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': "./media/"}),

    url(r'^api-auth/', include('rest_framework.urls',
                               namespace='rest_framework')),
]

trainings/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^diary/$', 'trainings.views.training_diary_current_month', name='diary_now'),
    url(r'^diary/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/$', views.DiaryTrainingsView.as_view(), name='diary'),
    url(r'^training/$', views.TrainingView.as_view(), name='training'),
]

templates/agile.html
{% load static %}

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
<script>
  $(document).ready(function() {
    $(".targetsColumn").sortable({
        // Для биндинга события при отпускания клавиши при изменения Приоритетов, Зон
        stop: function( event, ui ) {
            changePriority();
        }
    });
  });
</script>


<div id="agile_table" class="targetsColumn">
    {% for target in form.targets %}
        <div id="{{ form.PREFIX }}_{{ target.0 }}" class="draggable">
            {{ target.1 }}
        </div>
    {% endfor %}
</div>

templates/first_page.html
{% extends 'super5_base_site.html' %}
{% load static %}

{% block title %}Super5 главная страница{% endblock %}

{% block content %}
    <div class="all first_page">
        <div class="fp_side men_side"><img src="{% static 'uploads/fp_men.jpg' %}" width="100%" />
            <div class="fp_side_hover"></div>
            <div class="fp_side_content">
                <div class="fp_side_header">Для мужчин</div>
                <div class="fp_side_txt">Здесь будет какой-либо текст</div>
                <a href="" class="fp_side_btn">Далее</a>
            </div>
        </div>
        <div class="fp_side women_side"><img src="{% static 'uploads/fp_women.jpg' %}" width="100%" />
            <div class="fp_side_hover"></div>
            <div class="fp_side_content">
                <div class="fp_side_header">Для женщин</div>
                <div class="fp_side_txt">Здесь будет какой-либо текст</div>
                <a href="" class="fp_side_btn">Далее</a>
            </div>
        </div>
        <div class="fp_center">
            <div class="fpcenter_header">Здесь будет какой-либо текст</div>
            <div class="fpcenter_content">Здесь будет какой-либо текст</div>
        </div>
    </div>
{% endblock %}

templates/index.html
{% extends 'super5_base_site.html' %}
{% load static %}
{% block title %}Super5 - персональный мобильный фитнес-тренер{% endblock %}
{% block add_css %}
	<link href="{% static 'components/slick/slick.css' %}" rel="stylesheet">
{% endblock %}
{% block footer_js %}
	<!--slick-->
	<script src="{% static 'components/slick/slick.min.js' %}"></script>
	<script>
		$(document).ready(function(){
			$('.slick-index').slick({
				arrows: false,
				dots: true,
				autoplay: false,
				autoplaySpeed: 6000,
				asNavFor: '.slick-index-info'
			});
			$('<div class="slick-index_line-before"></div><div class="slick-index_line-after">').prependTo('.slick-dots');
			$('.slick-index-info').slick({
				arrows: false,
				dots: false,
				draggable: false,
				fade: true,
			});
		});


	</script>
{% endblock %}


{% block content %}
    <div class="all clearfix">
        <div class="content_container clearfix">
            <div class="content_row border_b4 clearfix">
				<div class="slider-l">

					<!--slick-index-->
					<div class="slick-index">
						{% for slide in slides %}
								<div class="slick-index_item">
									<img class="slick-index_img" src="{{ slide.photo_or_link }}" />
								</div>
						{% endfor %}
					</div>
					<!--slick-index-info-->
					<div class="slick-index-info">
						{% for slide in slides %}
							<div class="slick-index-info_item">
								<h2 class="slick-index-info_title">{{ slide.title }}</h2>
								<h3 class="slick-index-info_subtitle">{{ slide.under_title }}</h3>
								<p class="slick-index-info_text">{{ slide.body }}</p>
							</div>
						{% endfor %}
					</div>

            	</div>
            </div>


<!--
		   {% for post in posts %}
                {{ post.head }}
                {{ post.body }}
                {{ post.author }}
                {{ post.post_date }}
                {{ post.photo }}
                {{ post.video }}
                {{ post.title_main }}
                {{ post.body_main }}
            {% endfor %}
-->


<!--
			<div class="content_row clearfix flex_row">
				<div class="cell cell3-1"><img src="{% static 'uploads/home_photo1.jpg' %}" width="100%" /><div class="cell_content content_white"><a href="" class="cell_category">блог новостей</a><span class="cell_title">cross fit современные тренировки</span></div></div>
				<div class="cell cell3-1 cell_video"><img src="{% static 'uploads/home_photo2.jpg' %}" width="100%" /><div class="cell_content content_white"><a href="" class="cell_category">новое видео</a><span class="cell_title">cross fit современные тренировки</span></div><div class="cell_content content_black -css-animate"><i class="content_black_arrow"></i><span class="cell_text">Здесь будет какой-либо текст</span></div><i class="video_play"></i></div>
				<div class="cell cell3-1 cell_video"><img src="{% static 'uploads/home_photo3.jpg' %}" width="100%" /><div class="cell_content content_white"><a href="" class="cell_category">новое видео</a><span class="cell_title">cross fit современные тренировки</span></div><div class="cell_content content_black -css-animate"><span class="cell_text">Здесь будет какой-либо текст</span><i class="content_black_arrow"></i></div><i class="video_play"></i></div>
			</div>
-->

            <div class="content_row border_b4 clearfix flex_row">
				{% for post in posts %}
					<div class="cell cell4-1">
						<div class="cell_bg" role="img" style="background-image: url( {{ post.photo }} )"></div>
						<div class="cell_content content_white -css-animate">
							<a href="/blogs/" class="cell_category">блог новостей</a>
							<span class="cell_title">{{ post.title_main }}</span>
						</div>
						<div class="cell_content content_black -css-animate">
							<a href="/blogs/" class="cell_category">блог новостей</a>
							<span class="cell_title">{{ post.title_main }}</span>
							<span class="cell_text">{{ post.body_main }}</span>
						</div>
					</div>
				{% endfor %}
			</div>


            <div class="newsletter_container">
                <div class="newsletter_title">лента новостей</div>
                <div class="newsletter_text">Здесь будет какой-либо текст</div>
                <div class="newsletter_form">
                    <div class="newsletter_form_content">
                        <div class="newsletter_form_icon"></div>
                        <div class="newsletter_form_input"><input type="text" name="newsletter_mail" placeholder="your email adress"></div>
                        <div class="newsletter_form_submit">
                        	<button class="btn-search -p-index" name="search_btn">OK</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/initialization.html
{% extends 'super5_base_site.html' %}
{% load static %}

{% block title%}Super5 инициализация{% endblock %}

{% block content %}
    <div class="all stripedbkg clearfix">
        <div class="content_container clearfix">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="formpage_container initialization_container">
                    <div class="formpage_title">Данные пользователя</div>
                    <div class="form_container register_form">
                        {{ form.errors }}
                        <div class="form_row clearfix">
                            {{ form.height }}
                            {{ form.width }}
                        </div>
                        <div class="form_row clearfix">
                            <div class="birthday_container"><span>Д.р.:</span>
                                <input type="text" id="datepicker" name="{{ field.name }}" value="{{ form.birthday_title }}">
                            </div>
                            <div class="select_field_container clearfix">
                                <input class="select_value" type="hidden" name="gender" value="">
                                <div class="select_value_title">{{ form.gender_title }}</div><i class="select_btn"></i>
                                <ul class="select_list">
                                    {% for key, val in form.gender.field.choices %}
                                        <li data-select_val={{ key }}>{{ val }}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                        <div class="submit_container">
                            <input type="submit" class="form_submit" value="Дальше">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/personal_data_base.html
{% extends 'super5_base_site.html' %}
{% load static %}

{% block head_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/agile.js' %}"></script>
{% endblock %}

{% block title%}Super5 персональные данные{% endblock %}

{% block content %}
    <div class="all with_left_column clearfix stripedbkg -p-personalDataMaster">
        <div class="content_container clearfix">
            <div class="title_grey">Личные данные</div>

            <div class="formpage_container -p-personalDataMaster">
                {% block form %}
                {% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

templates/personal_data_base_fields.html
{% for field in form %}
    <div class="form_row clearfix -p-personalDataMaster">
        {% if field.errors %}
            {{ field.errors }}
        {% endif %}
        {% if field.label == 'Дата рождения' %}
            <input type="text" id="datepicker" name="{{ field.name }}" value="{{ form.birthday_title }}">
        {% elif field.label == 'Дни недели' %}
            <ul class="training-days-list">
                {% for field in form.week_day %}
                   <li class="training-days-list_item">
                        {{ field.tag }}
                       <label class="training-days-list_label" for="">
                            <span class="checkbox-square -training-days-list"></span>
                            <span class="training-days-list_day">{{ field.choice_label }}</span>
                        </label>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            {{ field }}
        {% endif %}
    </div>
{% endfor %}

templates/personal_data_master_form.html
{% extends 'personal_data_base.html' %}

{% load static %}

{% block form %}
	<div class="l-personalDataMaster -bobottom">
		<p class="wizard_step">Шаг {{ wizard.steps.step1 }} из {{ wizard.steps.count }}</p>
		<p class="wizard_params">{{ wizard.form.TITLE }}</p>
		{% if wizard.steps.step1 == 6 %}
			<p class="wizard_params -mt20">Выберите дни недели для занятий (Вам доступно <span class="wizard-days-count">{{ form.get_days_count }}</span>)</p>
		{% endif %}
	</div>
    <form action="" method="post" onsubmit="changePriority()">{% csrf_token %}
            {{ wizard.management_form }}
            {% if wizard.form.forms %}
                {{ wizard.form.management_form }}
                {% for form in wizard.form.forms %}
                    {{ form }}
                {% endfor %}
            {% else %}
                {% if wizard.steps.step1 == 1  or wizard.steps.step1 == 2  or wizard.steps.step1 == 3 or wizard.steps.step1 == 6 %}
                    {% with wizard.form as form %}
                        <div class="form_container">
                            {% include 'personal_data_base_fields.html' %}
                        </div>
                    {% endwith %}
                {% else %}
                    {% with wizard.form as form %}
						<div class="drag-list -p-personalDataMaster">
							{% include 'agile.html' %}
						</div>
                    {% endwith %}
                {% endif %}
            {% endif %}
		<div class="l-personalDataMaster -botop -mt -mb -pt">
        {% if wizard.steps.prev %}
			<button name="wizard_goto_step" type="submit" class="btn-grey -w250 -mr" value="{{ wizard.steps.first }}">Первый шаг</button>
			<button name="wizard_goto_step" type="submit" class="btn-grey -w250 -mr" value="{{ wizard.steps.prev }}">Назад</button>
        {% endif %}
			<input type="submit" class="btn-red -w250" value="Дальше"/>
		</div>
    </form>
{% endblock %}

templates/personal_data_simple_form.html
{% extends 'personal_data_base.html' %}

{% load static %}

{% block form %}
    <form method="post" enctype="multipart/form-data" onsubmit="changePriority()">
        {% csrf_token %}
        <div class="form_container">
        	<div class="form_container_col">
				{% include 'personal_data_base_fields.html' %}
            </div>
            <div class="form_container_col">
				{% if target_form %}
					{% with target_form as form %}
						<div class="dragndrop-list">
							<div class="dragndrop-list_title">{{ form.TITLE }}</div>
							{% include 'agile.html' %}
						</div>
					{% endwith %}
				{% endif %}
				{% if zone_form %}
					{% with zone_form as form %}
						<div class="dragndrop-list">
							<div class="dragndrop-list_title">{{ form.TITLE }}</div>
							{% include 'agile.html' %}
						</div>
					{% endwith %}
				{% endif %}
            </div>
            <div class="submit_container">
                <input type="submit" class="form_submit" value="Сохранить">
            </div>
        </div>
    </form>
{% endblock %}

templates/register.html
{% extends 'super5_base_site.html' %}
{% load static %}

{% block title %}Super5 регистрация{% endblock %}

{% block content %}
    <div class="all stripedbkg clearfix">
        <div class="content_container clearfix">
            <div class="formpage_container register_container">
                <div class="formpage_title">Регистрация в <span class="red_color">Super</span>5</div>
                <div class="form_container register_form">
                    <form method="post" enctype="multipart/form-data" novalidate>
                        {% csrf_token %}
                        <div class="form_row clearfix">
                            <div class="email_container">
                                {% if form.email.errors %}
                                    {{ form.email.errors }}
                                {% endif %}
                                {{ form.email }}
                            </div>
                        </div>
                        <div class="form_row clearfix">
                            {% if form.password.errors %}
                                {{ form.password.errors }}
                            {% endif %}
                            {{ form.password1 }}
                            {{ form.password2 }}
                        </div>

                        <div class="form_row clearfix">
                            <div class="separ_line_title"><span>или</span></div>
                        </div>
                        <div class="form_row clearfix">
                            <div class="socialreg_container">
                                <div class="social_title">Регистрация через социальные сети</div>
                                <ul class="social_icons">
                                    <li class="social_item">
                                        <a href="{% url 'social:begin' 'vk-oauth2' %}">
                                            <img src="{% static 'images/vk.png' %}" width="52" height="48" />
                                        </a>
                                    </li>
                                    <li class="social_item">
                                        <a href="{% url 'social:begin' 'facebook' %}">
                                            <img src="{% static 'images/facebook.png' %}" width="52" height="48" />
                                        </a>
                                    </li>
                                    <li class="social_item">
                                        <a href="{% url 'social:begin' 'google-oauth2' %}">
                                            <img src="{% static 'images/google.png' %}" width="52" height="48" />
                                        </a>
                                    </li>
                                    <li class="social_item">
                                        <a href="{% url 'social:begin' 'odnoklassniki-oauth2' %}">
                                            <img src="{% static 'images/ok.png' %}" width="52" height="48" />
                                        </a>
                                    </li>
                                    <li class="social_item">
                                        <a href="{% url 'social:begin' 'mailru-oauth2' %}">
                                            <img src="{% static 'images/mailru.png' %}" width="52" height="48" />
                                        </a>
                                    </li>
                                    <li class="social_item">
                                        <a href="{% url 'social:begin' 'yandex-oauth2' %}">
                                            <img src="{% static 'images/yandex.png' %}" width="52" height="48" />
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="submit_container">
                            <input type="submit" class="form_submit" value="Дальше">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/signin.html
{% extends 'super5_base_site.html' %}
{% load static %}

{% block title %}Super5 вход{% endblock %}

{% block content %}
    <div class="all stripedbkg clearfix">
        <div class="content_container clearfix">
            <div class="formpage_container signin_container">
                <div class="formpage_title">Авторизоваться в <span class="red_color">Super</span>5</div>
                <div class="form_container">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form_row clearfix">
                            {% if form.email.errors %}
                                {{ form.email.errors }}
                            {% endif %}
                            {{ form.email }}

                            {% if form.password.errors %}
                                {{ form.password.errors }}
                            {% endif %}
                            {{ form.password }}
                        </div>
                        <div class="submit_container">
                        	<input type="submit" class="form_submit" value="Вход">
                        	<span class="noaccount">У Вас нет аккаунта в SUPER5? <a href="{% url 'accounts:register' %}" class="red_color -upspeceficity">Создать</a></span>
                        </div>
                        <div class="form_row create_account -center">
                        	<a href="{% url 'password_reset' %}" class="red_color">Забыли пароль?</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/super5_base_site.html
<!doctype html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>{% block title %}{% endblock %}</title>

    {% block head_css %}
        <link href='http://fonts.googleapis.com/css?family=Roboto:400,400italic,700,700italic&subset=latin,cyrillic-ext' rel='stylesheet' type='text/css'>
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
        <link href="{% static 'css/style-makeup.css' %}" rel="stylesheet">
        <link href="{% static 'components/sweetalert/distt/sweetalert.css' %}" rel="stylesheet">
        <link href="{% static 'components/animatecss/animate.css' %}" rel="stylesheet">
        <link href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css" rel="stylesheet">
    {% endblock %}

    {% block add_css %}{% endblock %}

    {% block head_js %}
        <script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>
        <script type="text/javascript" src="{% static 'js/js.js' %}"></script>
        <script src="http://code.jquery.com/jquery-1.10.2.js"></script>
        <script src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
        <script>
            $(function() {
                $( "#datepicker" ).datepicker(
                        {
                            dateFormat: 'yy-mm-dd',
                            changeMonth: true,
                            changeYear: true,
                            yearRange: "-100:+0"
                        }
                );
            });
        </script>
    {% endblock %}
</head>

<body>
{% block navigate %}
    <nav class="clearfix">
        <div class="logo"><a href="{% url 'index_page' %}"><img src="{% static 'images/logo2.png' %}" width="155" height="117" /></a></div>
        <div class="main_menu">
            {% if user.is_authenticated %}
                <a href="{% url 'accounts:personal_data' %}" class="sign_inup -cutemail" title="{{ user.email }}">{{ user.email }}</a>
            {% else %}
                <a href="{% url 'accounts:login' %}" class="sign_inup">Вход</a>
            {% endif %}
            <ul>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'trainings:diary_now' %}">Тренировка</a></li>
                {% endif %}
                <li><a href="#">О Super5</a>
                    <ul>
                        <li><a href="#">Программа</a></li>
                        <li><a href="#">Почему я должен начать</a></li>
                        <li><a href="#">Тренировка</a></li>
                    </ul>
                </li>
                <li><a href="{% url 'how_it_works' %}">Как это работает</a></li>
                <li><a href="{% url 'author' %}">Об авторе</a></li>
                <li><a href="{% url 'blogs:feed' %}">Блог</a></li>
                <li><a href="{% url 'faq:index' %}">FAQ</a></li>
            </ul>
        </div>
        <div class="after_menu">
            <a href="{% url 'for_business' %}">Для бизнеса</a>
            <a href="{% url 'privacy_policy' %}">Политика приватности</a>
            <a href="{% url 'contacts' %}">Контакты</a>
        </div>
        <div class="share_btns">
            <a href="https://www.facebook.com/super5.co" target="_blank" class="share_btn_item facebook" title="Super5 в Facebook"></a>
            <a href="http://vk.com/super5co" target="_blank" class="share_btn_item vk" title="Super5 в VK"></a>
            <a href="http://www.youtube.com/channel/UCgdw_y0Z6jLwSJB5irtixFQ" target="_blank" class="share_btn_item youtube" title="Super5 на YouTube"></a>
        </div>


		<!--вызов modal2-->
		<button data-show-modal='modal2', data-animate-on-open='bounceInDown', data-animate-on-close='bounceOut'>modal2</button>
    </nav>
{% endblock %}

{% block user_pk %}
    <input type="hidden" name="user_pk" value="{{ user_pk }}">
{% endblock %}

{% block content %}
{% endblock %}

{% block footer %}
    <div class="footer_separ"></div>
    <div class="footer clearfix">
        <div class="phone_container"><span class="phone_icon"></span><a href="mailto:ask@super5.com"><span class="red_color">ask@super5.com</span></a></div>
        <div class="copyright_container">Copyright © 2015 Super5.co</div>
        <div class="totop" id="totop" title="Наверх">Наверх</div>
    </div>
{% endblock %}


	<!--modal2-->
	<div class="modal-c modal2">
<!--	обертка для позиционирования окна по центру-->
		<div class="modal-c_center">
	<!--		обертка для анимации тк позиционирование конфликт с анимацией в animate.css-->
			<div class="modal-c_animated animated">
				<div class="modal-c_close"></div>

				<div class="modal-c_content">
					<div class="modal-l1">Ваша заявка принята</div>
					<div class="modal-l2">Наш менеджер свяжется с Вами <br> в течении 15 минут.</div>
					<div class="modal-l3">
						<button class="btn-red -w250" type="button">Отправить</button>
					</div>
				</div>

			</div>
		</div>
	</div>


	<!--sweetalert-->
	<script src="{% static 'components/sweetalert/distt/sweetalert.min.js' %}"></script>
	<!--modal-->
	<script src="{% static 'components/modal/modal.js' %}"></script>

{% block footer_js %}{% endblock %}
</body>
</html>